JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dsearch.transitions.templateParaphrase=false -Dscoring.weights=eval/qa/models/blinkbath-2014-01-31-221632/model.3.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/eval/blinkbath-2014-01-31-221632-model.3.avg-trec.test-notemplates2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dsearch.transitions.relSyn=false -Dsearch.transitions.isaRelSyn=false -Dscoring.weights=eval/qa/models/blinkbath-2014-01-31-221632/model.3.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/eval/blinkbath-2014-01-31-221632-model.3.avg-trec.test-norelsyn2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="reverb|openie4" -Dscoring.weights=eval/qa/models/blinkbath-2014-01-31-221632/model.3.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/eval/blinkbath-2014-01-31-221632-model.3.avg-trec.test-noopenie2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="freebase" -Dscoring.weights=eval/qa/models/blinkbath-2014-01-31-221632/model.3.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/eval/blinkbath-2014-01-31-221632-model.3.avg-trec.test-nofreebase2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="probase" -Dscoring.weights=eval/qa/models/blinkbath-2014-01-31-221632/model.3.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/eval/blinkbath-2014-01-31-221632-model.3.avg-trec.test-noprobase2

