#shrooms-2014-02-04-101053/model.5.avg.txt

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dsearch.transitions.templateParaphrase=false -Dsearch.transitions.relSyn=false -Dsearch.transitions.parse=false -Dsearch.transitions.isaRelSyn=false -Dsearch.transitions.paralex=true -Dsearch.transition.ruleParaphrase=false -Dsearch.transitions.dropStops=true -Dscoring.weights=src/main/resources/edu/knowitall/search/qa/paralexWeights.txt -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/paralex-wikianswers.test

#JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dsearch.transitions.templateParaphrase=false -Dsearch.transitions.relSyn=false -Dsearch.transitions.parse=false -Dsearch.transition.isaRelSyn=false -Dsearch.transition.paralex=true -Dsearch.transition.ruleParaphrase=false -Dsearch.transitions.dropStops=false -Dscoring.weights=src/main/resources/edu/knowitall/search/qa/paralexWeights.txt -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/paralex-wikianswers.test

#JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dscoring.weights=src/main/resources/edu/knowitall/search/qa/defaultWeights.txt -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/defaultWeights-wikianswers.test


#JAVA_OPTS=-Xmx16g ./target/start -Dsearch.transitions.templateParaphrase=false -Dscoring.weights=eval/qa/models/shrooms-2014-02-04-101053/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/shrooms-2014-02-04-101053-model.5.avg-wikianswers.test-notemplates

#JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dsearch.transitions.relSyn=false -Dsearch.transitions.isaRelSyn=false -Dscoring.weights=eval/qa/models/shrooms-2014-02-04-101053/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/shrooms-2014-02-04-101053-model.5.avg-wikianswers.test-norelsyn
#
#JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="reverb|openie4" -Dscoring.weights=eval/qa/models/shrooms-2014-02-04-101053/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/shrooms-2014-02-04-101053-model.5.avg-wikianswers.test-noopenie
#
#JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="freebase" -Dscoring.weights=eval/qa/models/shrooms-2014-02-04-101053/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/shrooms-2014-02-04-101053-model.5.avg-wikianswers.test-nofreebase
#
#JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="probase" -Dscoring.weights=eval/qa/models/shrooms-2014-02-04-101053/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/wikianswers.test.txt eval/qa/output/shrooms-2014-02-04-101053-model.5.avg-wikianswers.test-noprobase
