#for i in `seq 4 10 | grep -v 5`; do
#JAVA_OPTS=-Xmx16g ./target/start -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.${i}.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.devtest.txt eval/qa/output/zoolook-2014-01-25-145518-model.${i}.avg-trec
#done
#
#JAVA_OPTS="-Xmx8g" ./target/start -Dscoring.weights=src/main/resources/edu/knowitall/search/qa/defaultWeights.txt -Dlearning.oracleMode=file -Dlearning.labelsPath=eval/qa/labels/labels.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 -Dlearning.inputsPath=<(head -1000 eval/qa/questions/webquestions.train.txt) -Dlearning.outputsPath=eval/qa/models -Dlearning.runName=crablegs edu.knowitall.learning.QaTrainer &>log.txt
#JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="reverb|openie4" -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/zoolook-2014-01-25-145518-model.5.avg-trec.test-noopenie
#JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="probase" -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/zoolook-2014-01-25-145518-model.5.avg-trec.test-noprobase
#JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="nell" -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/zoolook-2014-01-25-145518-model.5.avg-trec.test-nonell
#JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="freebase" -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/zoolook-2014-01-25-145518-model.5.avg-trec.test-nofreebase
#JAVA_OPTS=-Xmx16g ./target/start -Dsearch.transitions.relSyn=false -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/zoolook-2014-01-25-145518-model.5.avg-trec.test-norelsyn
#JAVA_OPTS=-Xmx16g ./target/start -Dsearch.transitions.relSyn=false -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/zoolook-2014-01-25-145518-model.5.avg-trec.test-norelsyn
#JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dscoring.weights=eval/qa/models/zoolook-2014-01-25-145518/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/zoolook-2014-01-25-145518-model.5.avg-trec.test-notemplatetypes

JAVA_OPTS=-Xmx16g ./target/start -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/trec.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-trec.test 

JAVA_OPTS=-Xmx16g ./target/start -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test 

JAVA_OPTS=-Xmx16g ./target/start -Dsearch.transitions.parse=false -Dsearch.transitions.templateParaphrase=false -Dsearch.transitions.relSyn=false -Dsearch.transitions.isaRelSyn=false -Dsearch.transitions.paralex=true -Dsearch.transitions.ruleParaphrase=false -Dsearch.transitions.dropStops=false -Dscoring.weights=src/main/resources/edu/knowitall/search/qa/paralexWeights.txt  -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/paralex-webquestions.test

JAVA_OPTS=-Xmx16g ./target/start -Dsearch.transitions.templateParaphrase=false -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test-notemplates

JAVA_OPTS=-Xmx16g ./target/start -Dsearch.transitions.relSyn=false -Dsearch.transitions.isaRelSyn=false -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test-norelsyn

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test-notemplatetypes

JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="reverb|openie4" -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test-noopenie

JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="freebase" -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test-nofreebase

JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="probase" -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test-noprobase

JAVA_OPTS=-Xmx16g ./target/start -Dtriplestore.skipNamespaces="nell" -Dscoring.weights=eval/qa/models/crablegs-2014-01-27-083838/model.5.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/eval/crablegs-2014-01-27-083838-model.5.avg-webquestions.test-nonell
