JAVA_OPTS=-Xmx16g ./target/start -Dsearch.transitions.templateParaphrase=false -Dscoring.weights=eval/qa/models/sugarcrisp-2014-01-29-192116/model.1.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/sugarcrisp-2014-01-29-192116-model.1.avg-webquestions.test-notemplates2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dsearch.transitions.relSyn=false -Dsearch.transitions.isaRelSyn=false -Dscoring.weights=eval/qa/models/sugarcrisp-2014-01-29-192116/model.1.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/sugarcrisp-2014-01-29-192116-model.1.avg-webquestions.test-norelsyn2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="reverb|openie4" -Dscoring.weights=eval/qa/models/sugarcrisp-2014-01-29-192116/model.1.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/sugarcrisp-2014-01-29-192116-model.1.avg-webquestions.test-noopenie2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="freebase" -Dscoring.weights=eval/qa/models/sugarcrisp-2014-01-29-192116/model.1.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/sugarcrisp-2014-01-29-192116-model.1.avg-webquestions.test-nofreebase2

JAVA_OPTS=-Xmx16g ./target/start -Dparaphrase.template.useTypes=false -Dtriplestore.skipNamespaces="probase" -Dscoring.weights=eval/qa/models/sugarcrisp-2014-01-29-192116/model.1.avg.txt -Dparsing.cg.lexicalRuleKeep='^fullPattern|^.*Identity$' -Dparaphrase.template.maxHits=100 -Dsearch.maxSearchTimeSec=20 edu.knowitall.eval.qa.QASystemRunner eval/qa/questions/webquestions.test.txt eval/qa/output/sugarcrisp-2014-01-29-192116-model.1.avg-webquestions.test-noprobase2
